#!/bin/bash
# some duplicates, bcs they sometimes are located elsewhere
sleep 1
killall xdg-desktop-portal-hyprland
killall xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
/usr/lib/systemd/user/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &
/usr/lib/systemd/user/xdg-desktop-portal &
